### ISSUE TITLE
Error when using object in the store

### ISSUE THREAD

**Issue by robertgirschick** [wobsoriano/pinia-shared-state#13]
There seems to occur an error in the receiver instance when the sender is loaded and a nested object is in the store (even if it not used anywhere).

```js
const useStore = defineStore({
  id: 'shared',
  state: () => ({
    foo: {
      bar: 123
    }    
  }),
  share: {  
    enable: true,
  },
});
```
This causes the following error in the listening instance:

![image](https://user-images.githubusercontent.com/11800804/179544261-079fe146-8e35-4e87-918f-1ede90d88fde.png)

No error here:
```js
const useStore = defineStore({
  id: 'shared',
  state: () => ({
    foo: 123,
    bar: 123
  }),
  share: {  
    enable: true,
  },
});
```
Is there a problem with using non-primitives in the state?

**Comment by wobsoriano** [comment]
Thanks for reporting!

Can you try v0.2.7?

**Comment by robertgirschick** [comment]
Yes, the error is gone if I use v0.2.7+.

Thanks!
