### ISSUE TITLE
Composition API and Typescript example

### ISSUE THREAD

**Issue by stefnotch** [wobsoriano/pinia-shared-state#14]
It'd be lovely to have an example on the Readme that works with the Pinia composition API and with Typescript.

Here's the relevant bit of the Pinia documentation https://pinia.vuejs.org/core-concepts/plugins.html#typescript

**Comment by stefnotch** [comment]
Adding the `share` property makes Typescript rather unhappy at the moment.
![image](https://user-images.githubusercontent.com/10220080/180657299-7f9e51ff-c37f-4335-a5d1-6ee140103db4.png)

**Comment by wobsoriano** [comment]
Should work with latest versions now.
