### ISSUE TITLE
[Question] What is 'native' type?

### ISSUE THREAD

**Issue by peter-mghendi** [wobsoriano/pinia-shared-state#15]
Hi there :wave:!

I'm considering using this package and I noted an issue in the README.

[In your README](https://github.com/wobsoriano/pinia-shared-state/blob/e6b3ac5f94b9f14780c3093b4eac868845d9c4fe/packages/pinia-shared-state/README.md?plain=1#L29), with no explanation on the implications of each option.

Digging around the source a little, I've found that it's [being passed as-is](https://github.com/wobsoriano/pinia-shared-state/blob/e6b3ac5f94b9f14780c3093b4eac868845d9c4fe/packages/pinia-shared-state/src/index.ts#L35) to [broadcast-channel](https://github.com/pubkey/broadcast-channel), and had to go there for documentation.

>**Note**
>I'm willing to add a link or a note in the README to send users to the documentation for this.

Secondly, I'd like to confirm whether this plugin supports the automatic method selection mentioned in [broadcast-channel documentation](https://github.com/pubkey/broadcast-channel#methods).

Thanks.

**Comment by AndreiSoroka** [comment]
hi
@sixpeteunder I created PR https://github.com/wobsoriano/pinia-shared-state/pull/17 for the same topic

**Comment by AndreiSoroka** [comment]
After your link I understood:
- https://github.com/wobsoriano/pinia-shared-state/blob/master/packages/pinia-shared-state/src/index.ts#L31
- https://github.com/wobsoriano/pinia-shared-state/blob/master/packages/pinia-shared-state/src/index.ts#L105

We can remove the default value and it will work

**Comment by AndreiSoroka** [comment]
@wobsoriano hi! Can you check PR: https://github.com/wobsoriano/pinia-shared-state/pull/19/files ?

**Comment by wobsoriano** [comment]
Merged https://github.com/wobsoriano/pinia-shared-state/pull/19
