### ISSUE TITLE
BroadcastChannel is not defined

### ISSUE THREAD

**Issue by dolbex** [wobsoriano/pinia-shared-state#18]
I'm getting an odd error in Nuxt 3 (very close to following your demo) and I'm getting `BroadcastChannel is not defined` in `native.js`. If I add the import at the top I no longer get the error (but I do get an error that `PQueue is not a constructor`. I'm sure I'm doing something wrong but just wanted to see if you had any ideas on what it might be.

Just for reference the code below seems to "fix" it. 

```
import { microSeconds as micro, PROMISE_RESOLVED_VOID } from '../util.js';
import { BroadcastChannel } from 'broadcast-channel';

export var microSeconds = micro;
export var type = 'native';
export function create(channelName) {
  var state = {
    messagesCallback: null,
    bc: new BroadcastChannel(channelName),
    subFns: [] // subscriberFunctions

  };
  ```

**Comment by dolbex** [comment]
Little more investigation it does appear that even a baseline install is having this issue. I would really appreciate it if you have any direction here. Happy to donate to the project as it's an awesome solution to what I'm working on.

**Comment by oleghalin** [comment]
Face same issue on browsers which dont support broadcast-channel

**Comment by wobsoriano** [comment]
Sorry for the late response. To make it work with Nuxt, you need to add a `.client` suffix in the file name to load it only on the client-side. 

`~/plugins/shared-state.client.ts`

```js
import { PiniaSharedState } from 'pinia-shared-state';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$pinia.use(PiniaSharedState({
    enable: true,
  }));
});
```

For browsers without broadcast-channel support, you have two options:

1. [Polyfill](https://github.com/alexis89x/broadcast-channel) it
2. Use localStorage as the [type](https://github.com/wobsoriano/pinia-shared-state#usage).
