### ISSUE TITLE
Consider adding some sort of persistence

### ISSUE THREAD

**Issue by carbotaniuman** [wobsoriano/pinia-shared-state#2]
It would be difficult to integrate this into a persistence solution without causing a bunch of repeated updates, and as vuex-multi-tab-state automatically persists due to how it shares data, it makes sense for this to also persist.

**Comment by wobsoriano** [comment]
This plugin uses the BroadcastChannel API. If I were to add persistence, it's better to just ditch broadcastchannel and use localStorage + event listeners instead.

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/pinia-shared-state/commit/35ee3cacd3dd535dc54a79025c5627cc27839295
