### ISSUE TITLE
Plugin seems to be working but not sharing state

### ISSUE THREAD

**Issue by tomburge** [wobsoriano/pinia-shared-state#20]
I have installed the plugin into a Quasar project. My Pinia index file has this code: 

`pinia.use(PiniaSharedState)`

The plugin creates pubkey keys in local storage for both of my stores

![image](https://user-images.githubusercontent.com/39355437/210184110-c0084e14-b546-4ad9-b29f-1cd240e192fd.png)

Here is a screenshot of both browsers. This is latest version of Chrome as well.

The other browser tab does not update the state when it changes in the other browser tab.

![image](https://user-images.githubusercontent.com/39355437/210184181-12a4c71d-370b-4ca9-aaba-54907e05732b.png)

I tried the example pinia.use from the README.md and I get this error:

![image](https://user-images.githubusercontent.com/39355437/210184222-2ea55897-598b-41e5-8ca2-8548f90dc20b.png)

I have tried in Firefox as well and same issue.

**Comment by wobsoriano** [comment]
Hey, do you mind sharing a repro I can play with? Thanks!

**Comment by kayatao** [comment]
Hi,
I've faced the same issue when I shared model instance which is retrieved from amplify datastore.
However, this issue happens on version 0.30 but on version 0.2.14 it worked fine.
On v.0.2.14, the shared object looks like this.
<img width="958" alt="Screenshot 2023-01-31 at 14 01 30" src="https://user-images.githubusercontent.com/13063717/215691587-3d549010-1dd8-4a6e-9b52-8efb9c40ffed.png">

**Comment by raimondas-breachgg** [comment]
I can confirm what @kayatao said. There is something in 0.3 that sometimes breaks everything

**Comment by jd1378** [comment]
~~I'm experiencing a similar issue, which I don't understand why~~

Ignore this, there was a problem with my own code. it is working fine for me.

**Comment by wobsoriano** [comment]
Hi, please try the latest version. It uses `toRaw` now :)

Feel free to open it if the issue persists!
