### ISSUE TITLE
Bloat with recent patch (0.2.13)

### ISSUE THREAD

**Issue by sphinxrave** [wobsoriano/pinia-shared-state#21]
With Realistic-Structured-Clone the compiled output bloats by about 50kb minified, or 2.5x the old size gzipped. Is there something it solves?

Just want to bring that up and see if there are alternatives we can explore that doesn't cause this kind of bloating.

Also curious if there's interest in a version that just uses Broadcast-Channel native. In my application, sharing state is a nice-to-have, but not super critical. Plus Broadcast-Channel API is now widely available. 

![image](https://user-images.githubusercontent.com/62570796/213954571-f094347a-f518-4582-8f0b-bc538c0bb011.png)

at 92% of all users and most modern browsers.

**Comment by wobsoriano** [comment]
Wow that’s really big. Thank you for reporting that!

**Comment by wobsoriano** [comment]
Hi! Can you update and let me know what size are you getting now? Thanks!

**Comment by sphinxrave** [comment]
LGTM! https://bundlephobia.com/package/pinia-shared-state@0.2.14

![image](https://user-images.githubusercontent.com/62570796/214226105-ec807a9e-c914-4002-acac-fab42d867c7b.png)

Thanks for the quick turnaround 👍
