### ISSUE TITLE
object|null store properties not tracked after set to null

### ISSUE THREAD

**Issue by thor-juhasz** [wobsoriano/pinia-shared-state#23]
It seems that if I define a store like this:

```typescript
const useUserStore = defineStore('user', () => {
    const user = ref<User | null>(null);

    // ...
});
```

it will no longer update across tabs if it gets set to `null`.
For example:
1. User logs in
2. User opens multiple tabs
3. User logs out in one tab (other tabs correctly reflect that)
4. User logs in again (other tabs do not get that update)

**Comment by thor-juhasz** [comment]
A little extra:
If user refreshes the page after step 4, or takes any other action that updates the store user again, other tabs will get the update.

**Comment by wobsoriano** [comment]
This should be fixed in the latest versions. Please feel free to open it if you still encounter this!
