### ISSUE TITLE
add support for adding as a nuxt 3 module

### ISSUE THREAD

**Issue by jd1378** [wobsoriano/pinia-shared-state#25]
it would be nice if we could add a nuxt module for using the plugin

you can take a look at [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/packages/nuxt/src/runtime/plugin.ts) for reference

**Comment by pronchik** [comment]
Yeah, it will be so good!

**Comment by frostycoles** [comment]
I added it as a plugin and it seems to work: https://github.com/wobsoriano/pinia-shared-state/issues/31#issuecomment-1875829478

**Comment by wobsoriano** [comment]
No plans on a nuxt module, but it should be easy to implement a plugin out of it - https://github.com/wobsoriano/pinia-shared-state/blob/main/examples/nuxt3/plugins/shared-state.ts
