### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by timbze** [wobsoriano/pinia-shared-state#26]
Not sure if I'm doing something wrong. I did see #14 and that it should be fixed but am not sure what I am doing wrong.

I ran `npm install pinia-shared-state --save`

In my main.ts I have
```ts
import {PiniaSharedState} from "pinia-shared-state"
const pinia = createPinia()
pinia.use(PiniaSharedState({
  initialize: false,
  enable: false
}))
```

The "pinia-shared-state" part is red-underlined with error: 

> TS7016: Could not find a declaration file for module 'pinia-shared-state'. '/home/app/src/VueClient/node_modules/pinia-shared-state/dist/index.mjs' implicitly has an 'any' type.   There are types at '/home/app/src/VueClient/node_modules/pinia-shared-state/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'pinia-shared-state' library may need to update its package.json or typings.

In my pinia store I'm trying to add the "share" but I get this error:
> TS2345: Argument of type '{ id: "user-auth"; state: () => { user: any; securities: { customRoleId: string; authCategory: string; permissionScope: number; }[]; }; getters: { isAuthenticated(): boolean; getAccessToken(): string; getUserName(): string; }; actions: { ...; }; persist: { ...; }; share: { ...; }; }' is not assignable to parameter of type 'DefineStoreOptions<"user-auth", { user: any; securities: { customRoleId: string; authCategory: string; permissionScope: number; }[]; }, { isAuthenticated(): boolean; getAccessToken(): string; getUserName(): string; }, { ...; }>'.   Object literal may only specify known properties, and 'share' does not exist in type 'DefineStoreOptions<"user-auth", { user: any; securities: { customRoleId: string; authCategory: string; permissionScope: number; }[]; }, { isAuthenticated(): boolean; getAccessToken(): string; getUserName(): string; }, { ...; }>'.

**Comment by wobsoriano** [comment]
Thanks! Fixed.

**Comment by timbze** [comment]
> Thanks! Fixed.

Now it works. Thank you!
