### ISSUE TITLE
stringify non-POJOS error

### ISSUE THREAD

**Issue by awesome-scott** [wobsoriano/pinia-shared-state#29]
I can't seem to figure out why adding this to my Vue3 project produces the error:

stringify.js:138 Uncaught (in promise) DevalueError: Cannot stringify arbitrary non-POJOs
    at flatten (stringify.js:138:13)
    at stringify (stringify.js:178:16)
    at d (index.mjs:1:144)
    at watch.deep (index.mjs:1:323)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at job (runtime-core.esm-bundler.js:1756:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:32)
    at flushJobs (runtime-core.esm-bundler.js:357:9)
    
   Any help would be appreciated...
   
   "vue": "^3.3.4",
   "pinia-shared-state": "^0.4.5",

**Comment by wobsoriano** [comment]
Would be nice to have a simple repro. Can you do it via stackblitz?

**Comment by awesome-scott** [comment]
Disregard. I simply had an issue with incoming data. I just needed to destructure it with `JSON.parse(JSON.stringify(data))`

**Comment by TheGodlyLuzer** [comment]
I have the same issue, where did you put the fix?

**Comment by wobsoriano** [comment]
@TheGodlyLuzer , would you be able to provide a basic reproduction?

**Comment by TheGodlyLuzer** [comment]
Surely, i just have a really basic setup


Store Plugin
```js
import {App} from "vue";
import {createPinia, Pinia} from "pinia";
import {PiniaSharedState} from "pinia-shared-state";

export default {
    install(app: App){
        const pinia: Pinia = createPinia();
        pinia.use(PiniaSharedState({
            enable: true,
            initialize: false,
            type: 'localstorage',
        }))

        app.use(pinia);
    }
}
```

App
```js
import {createApp, App as Application} from 'vue';
import App from './App.vue';
import './styles.css';

import storePlugin from "./plugins/store-plugin.ts";

let app: Application = createApp(App);

app.use(storePlugin);

app.mount('#app');
```

Thats it :)

**Comment by kolaente** [comment]
Hitting the same error. Debugged into it and it seems like the object where stringify fails is a Vue Proxy. Shouldn't this work at least when using a broadcast channel without manually serializing it?

Here's a screenshot from the debugger:

![image](https://github.com/wobsoriano/pinia-shared-state/assets/13721712/548b6091-5648-49d1-9916-b9e3f4960428)

**Comment by timbze** [comment]
Looks like this issue comes from using the devalue library. devalue does not work for non-POJOs, which can be classes with constructors from what I understand. But it seems my zod objects are also non-POJOs. I wonder if the best solution here would be that we could set our own serializer and deserializer, like the [pinia-persist](https://prazdevs.github.io/pinia-plugin-persistedstate/guide/config.html#serializer) lib does for example.

Also, devalue is designed this way. See author comment [here](https://github.com/Rich-Harris/devalue/issues/15#issuecomment-427533207).

**Comment by wobsoriano** [comment]
@timbze good idea to have a custom serializer/deserializer

**Comment by wobsoriano** [comment]
I opened a PR that should fix this. I would be happy if anyone's available to review it.

https://github.com/wobsoriano/pinia-shared-state/pull/34/

**Comment by timbze** [comment]
> I would be happy if anyone's available to review it. 

I would be happy to help test

**Comment by wobsoriano** [comment]
@timbze I dont have any tests written but you can run `pnpm dev` and it should run the vite app side-by-side with the plugin

**Comment by wobsoriano** [comment]
I'm planning to merge [the PR](https://github.com/wobsoriano/pinia-shared-state/pull/34) by the weekend :)
