### ISSUE TITLE
Allow to provide BroadcastChannel implementation

### ISSUE THREAD

**Issue by bisubus** [wobsoriano/pinia-shared-state#3]
The suggestion is to allow custom BroadcastChannel implementation, notably https://github.com/pubkey/broadcast-channel 

>This is not a polyfill. Do not set this module to window.BroadcastChannel. This implementation behaves similiar to the BroadcastChannel-Standard with these limitations:
>
> You can only send data that can be JSON.stringify-ed.
> 
> While the offical API emits onmessage-events, this module directly emitts the data which was posted

As mentioned, it's unsafe to polyfill BroadcastChannel with incompliant implementation. It can affect other page scripts that do feature detection.

It could be implemented by adding new options:

```js
BroadcastChannel: BroadcastChannelImpl,
eventTransform: data => ({ data }),
```

Also related to #2 as BroadcastChannel shim is implemented through localStorage.

**Comment by wobsoriano** [comment]
I'll check that out. Thanks.

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/pinia-shared-state/commit/35ee3cacd3dd535dc54a79025c5627cc27839295

**Comment by bisubus** [comment]
Currently relying on `broadcast-channel` looks reasonable, because native BC is unavailable in Safari. Maybe it would be better to make the dependency optional in future and make users specify the implementation themselves, e.g. with options that were suggested above.
