### ISSUE TITLE
Sync problmes

### ISSUE THREAD

**Issue by joseneves-dev** [wobsoriano/pinia-shared-state#30]
Hi everyone, frist off amazing plugin!

i am facing issues with some sync with in the tabs. 
For exemple if i stop working with chrome for 3 or 4 minutes and have multiple tabs, when i get back and try to change something it will stop sync.

Also when i have 2 or more open tabs and stop working with them, after 2 minutes or more, if i open a new tab it will be off sync from the others!

is this normal ?

**Comment by wobsoriano** [comment]
Hi, are you still able to reproduce this issue? If yes, can you make a repro via stackblitz?

**Comment by wobsoriano** [comment]
Feel free to reopen!
