### ISSUE TITLE
How can i work this in nuxt3

### ISSUE THREAD

**Issue by Ischafak** [wobsoriano/pinia-shared-state#31]
when i try 
import { share, unshare } from 'pinia-shared-state'; i instantly get error

**Comment by Ischafak** [comment]
ok i figure out i get error because of unshare 
<img width="1038" alt="image" src="https://github.com/wobsoriano/pinia-shared-state/assets/13226879/e7a22431-b9c5-474c-a51d-b775742ee702">

<img width="1182" alt="image" src="https://github.com/wobsoriano/pinia-shared-state/assets/13226879/2080a210-098c-402f-ab19-b29103ef335c">

**Comment by frostycoles** [comment]
@Ischafak I got it to work as a plugin:

```
// ~/plugins/pinia-shared-state.ts
import { PiniaSharedState } from 'pinia-shared-state';

export default defineNuxtPlugin((nuxtApp: any) => {
  nuxtApp.$pinia.use(
    PiniaSharedState({
      enable: true,
      initialize: true,
      type: 'localstorage'
    })
  );
});
```

Versions:
```
"@pinia/nuxt": "^0.4.7",
"nuxt": "^3.2.2",
"pinia-shared-state": "^0.5.1"
```

**Comment by wobsoriano** [comment]
Using it manually should be like this, sorry for the incorrect usage in readme:

```ts
import { onMounted, onUnmounted } from 'vue'
import { share } from 'pinia-shared-state'
import useStore from './store'

const counterStore = useStore()

onMounted(() => {
  const { unshare } = share('counter', counterStore, { initialize: true })

  onUnmounted(() => {
    // Call `unshare` method to close the channel
    unshare()
  })
})
```

If you want to use it with nuxt as a plugin, you can follow @frostycoles's advice
