### ISSUE TITLE
Continue sharing state in minimized window

### ISSUE THREAD

**Issue by lannodev** [wobsoriano/pinia-shared-state#35]
How to continue sharing state when window is minimized?
In the example below I have kept the window minimized while increasing the number

![image](https://github.com/wobsoriano/pinia-shared-state/assets/12519008/3c901da7-d7c3-4c87-adf2-84ca2881b7a3)

**Comment by lannodev** [comment]
I found a solution for my electron app:

```javascript
mainWindow = new BrowserWindow({
  webPreferences: {
    backgroundThrottling: false,
  },
});
```

**Comment by wobsoriano** [comment]
Awesome, thanks for sharing your solution!
