### ISSUE TITLE
Incompatible typescript error

### ISSUE THREAD

**Issue by dominikklein** [wobsoriano/pinia-shared-state#4]
I have the following error message when i try to use the plugin in my app:

`store.use(PiniaSharedState({ enable: true, initialize: false }))`:

```
Argument of type '({ store, options }: PiniaPluginContext<string, StateTree, _GettersTree<StateTree>, _ActionsTree>) => void' is not assignable to parameter of type 'PiniaPlugin'.
  Types of parameters '__0' and 'context' are incompatible.
...
```

Is it no longer compatible with the current pinia version?

**Comment by wobsoriano** [comment]
Updated pinia version. Can you try again?

**Comment by dominikklein** [comment]
Thanks , now it's working 👍
