### ISSUE TITLE
Consider allowing broadcast-channel to select transport method

### ISSUE THREAD

**Issue by Nulifier** [wobsoriano/pinia-shared-state#6]
On the following lines an explicit option for the transport type of broadcast-channel is provided. That library will select the appropriate type based on browser support and will use the faster Broadcast Channel API on [~75%](https://caniuse.com/broadcastchannel) of browsers. This should have no affect on users who don't have support and provide an instant speed up for most users.

https://github.com/wobsoriano/pinia-shared-state/blob/40ae9154352fdcabc024a537c67912307db0ff7e/packages/plugin/src/index.ts#L30-L32

**Comment by wobsoriano** [comment]
Ive been planning on this. Will take a look at it later

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/pinia-shared-state/commit/e029e1b980ff4b15fcc255ed751cb500bf84c6fc
